apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-deployment
  namespace: default  # Ensure the correct namespace is specified or default if no specific namespace is required
  labels:
    app: fast-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fast-api
  template:
    metadata:
      labels:
        app: fast-api
    spec:
      containers:
      - name: fast-api
        image: tc349/streaming-data-api:v2
        ports:
        - containerPort: 5310
        env:
        - name: ENDPOINT
          value: "${env.ENDPOINT}"
        - name: USER
          value: "${env.USER}"
        - name: PASSWORD
          value: "${env.PASSWORD}"
        - name: PORT
          value: "${env.PORT}"
        - name: DATABASE
          value: "${env.DATABASE}"