apiVersion: v1
kind: Service
metadata:
  name: fast-api-service
  labels:
    app: fast-api
spec:
  selector:
    app: fast-api
  ports:
    - protocol: TCP
      port: 80           # The port the service will expose
      targetPort: 5310   # The port the Flask API is running on inside the container
  type: LoadBalancer     # Use LoadBalancer for external access to the service