apiVersion: batch/v1
kind: Job
metadata:
  name: rf-train
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      name: rf-train-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-8-235.eu-west-2.compute.internal
      restartPolicy: Never
      containers:
      - name: rf-trainer-container
        image: rdv100/train_rf:1.1
        volumeMounts:
        - name: model-output
          mountPath: /app/output
      volumes:
      - name: model-output
        hostPath:
          path: /home/ec2-user/BigData_May/bd_class_project/ml/all_ml/model
          type: DirectoryOrCreate
