apiVersion: apps/v1
kind: Deployment
metadata:
  name: rf-predict-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rf-model
  template:
    metadata:
      labels:
        app: rf-model
    spec:
      containers:
      - name: rf-model-container
        image: usman57/fraud-model:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: rf-model-service
spec:
  selector:
    app: rf-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
