pipeline {
    agent any
    stages {
        stage('Run Producer and Consumer Jobs') {
            parallel {
                stage('Producer Job') {
                    steps {
                        build job: 'kafka_buildjar_producer'
                    }
                }
                stage('Consumer Job') {
                    steps {
                        build job: 'kafka_realtime_consumer'
                    }
                }
            }
        }
    }
}

