apiVersion: batch/v1
kind: CronJob
metadata:
  name: fraud-predict-cron
spec:
  # run the job every minute
  schedule: "*/1 * * * *"
  # don’t start a new job if the previous is still running
  concurrencyPolicy: Forbid
  # if the controller is down or misses a schedule, only retry for 30s
  startingDeadlineSeconds: 30

  jobTemplate:
    spec:
      # retry twice on failure
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: fraud-predicter
            image: rdv100/predict_fraud:2.1
            imagePullPolicy: IfNotPresent
            env:
            - name: HIVE_METASTORE_URIS
              value: "thrift://18.134.163.221:9083"
            volumeMounts:
            - name: model
              mountPath: /app/model
          volumes:
          - name: model
            hostPath:
              path: /home/ec2-user/BigData_May/bd_class_project/ml/all_ml/model
              type: Directory
